---
output: html_document
---
# Информатика

Данный сайт предназначен для материалов по информатике в РАНХиГС.

- [Оформление задачи](of.html)
- [Баллы за семестр](score.html)

Структура:

- [s1 - задачи первого семестра](s1/).
- [s2 - задачи второго семестра](s2/).

Прочая информация:

- [новая бально-рейтинговая система](rating.html)

Список литературы по программированию на R:

1. [EN] "R in Action, Second Edition. Data analysis and graphics with R", Robert Kabacofа
    + [RU] R в действии. Анализ и визуализация данных на языке R. Автор: Роберт И. Кабаков Переводчик: Полина Волкова
2. Много других книг

Список полезных ресурсов:

1. [Официальный сайт](https://www.r-project.org) - для скачивания основного пакета
2. [RStudio](https://www.rstudio.com) - интерфейс для R. Удобно работать
3. [Google's R Style Guide](http://google-styleguide.googlecode.com/svn/trunk/Rguide.xml#assignment) - как оформлять код для читабельности.
4. [R-bloggers](http://www.r-bloggers.com) - блог по программированию в R.

Тут я буду что-то коллекционировать для себя по `Rmd`: [leonovmx.github.io/info/for_rmd.html](for_rmd.html)


Соответственно примеры `Rmd` можно найти в самом депозитарии.
Если у вас есть что-то крутое и интересное - шлите, добавлю.
Нужно как минимум:

1) инструкция по md
2) инструкция по rmd



---

Если найдёте ошибку, неточность, неработающую ссылку, материал, 
которые вас оскорбляет, сообщите. Может исправлю.

